runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /
  script: main.app

- url: /create
  script: main.app

- url: /decode
  script: main.app

env_variables:
  # Add any environment variables your application needs here, if any.
  # For example:
  # VAR_NAME: "value"

automatic_scaling:
  min_instances: 1
  max_instances: 1

instance_class: F1

runtime_config:
  python_version: 3
